TemplateData in match method shouldnt be required as original version's way
EdJoPaTo/telegraf-i18n pull request #1
Opened 2020-11-07 21:15 UTC by jfkz

I found your module very useful and add one tune from myself: as in original version match has to have 1 required parameter and 1 optional, for compatibility reasons.
I fix this way, pls review.

2020-11-09 10:00 UTC, EdJoPaTo requested changes
Makes sense!
I never used `match` or `reply` so thanks for taking a look!

2020-11-09 10:00 UTC, EdJoPaTo commented on source/i18n.ts
> +  return (text, ctx) => (text && ctx?.i18n && text === ctx.i18n.t(resourceKey, templateData || {})) ? [text] : null
the `ctx.i18n.t()` method already has an optional second argument so I would prefer using its way of handling the not provided templateData. So the match keeps to be a shortcut and `ctx.i18n.t()` knows how to deal with `undefined` as second argument.

https://github.com/EdJoPaTo/telegraf-i18n/blob/d1e03688f6ad76ae4b4a0cc58308a29c62304c1f/source/context.ts#L40

```suggestion
  return (text, ctx) => (text && ctx?.i18n && text === ctx.i18n.t(resourceKey, templateData)) ? [text] : null
```

2020-11-09 11:06 UTC, jfkz commented on source/i18n.ts
> +  return (text, ctx) => (text && ctx?.i18n && text === ctx.i18n.t(resourceKey, templateData || {})) ? [text] : null
Yeah, ofc. I did only quick look over the code, so you can modify my commits as you wish.

2020-11-10 14:34 UTC, merged

2020-11-10 14:35 UTC, EdJoPaTo commented
Thanks for your time checking out the PR and providing the fix!